# Importing the necessary libraries

In [9]:
import numpy as np

# Step 1: Generating a random matrix of MxN dimensions (M features, N samples)

In [10]:
M, N = 5, 10
matrix = np.random.rand(M, N)

# Step 2: Computing the covariance matrix


In [11]:
# cov_matrix = np.cov(matrix)
cov_matrix = np.round(np.cov(matrix), 2)

# Step 3: Computing the correlation matrix


In [12]:
# corr_matrix = np.corrcoef(matrix)
corr_matrix = np.round(np.corrcoef(matrix), 2)

#Precision

In [13]:
# np.set_printoptions(precision=2)

# Step 4: Output


In [14]:
# print(f"Matrix (MxN):\n{matrix:.3f}")
# print(f"Covariance Matrix:\n{cov_matrix:.3f}")
# print(f"Correlation Matrix:\n{corr_matrix:.3f}")
print(f"Matrix (MxN):\n{np.round(matrix, 2)}")
print(f"Covariance Matrix:\n{cov_matrix}")
print(f"Correlation Matrix:\n{corr_matrix}")

Matrix (MxN):
[[0.75 0.82 0.28 0.74 0.2  0.46 0.15 0.24 0.96 0.55]
 [0.3  0.25 0.58 0.68 0.82 0.18 0.85 0.13 0.27 0.39]
 [0.91 0.13 0.59 0.15 0.54 0.15 0.33 0.84 0.19 0.75]
 [0.34 0.36 0.44 0.46 0.64 0.05 0.34 0.93 0.36 0.51]
 [0.93 0.31 0.6  0.78 0.43 0.05 0.96 0.57 0.56 0.97]]
Covariance Matrix:
[[ 0.09 -0.04 -0.03 -0.02 -0.  ]
 [-0.04  0.07 -0.01  0.    0.03]
 [-0.03 -0.01  0.09  0.04  0.04]
 [-0.02  0.    0.04  0.05  0.02]
 [-0.    0.03  0.04  0.02  0.09]]
Correlation Matrix:
[[ 1.   -0.45 -0.34 -0.37 -0.01]
 [-0.45  1.   -0.12  0.06  0.38]
 [-0.34 -0.12  1.    0.56  0.48]
 [-0.37  0.06  0.56  1.    0.23]
 [-0.01  0.38  0.48  0.23  1.  ]]
